// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.migration.version", 165);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1781022874);
user_pref("browser.search.region", "BR");
user_pref("datareporting.dau.cachedUsageProfileGroupID", "355d6204-d86d-4a96-9517-ae20b5be34ba");
user_pref("datareporting.dau.cachedUsageProfileID", "f6b0055f-6f5c-451e-b244-0e5fb69b913f");
user_pref("distribution.canonical-002.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "149.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-en-US@firefox.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20260404010525");
user_pref("extensions.lastAppVersion", "149.0.2");
user_pref("extensions.lastPlatformVersion", "149.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"9d6188c6-ed55-4da2-aa33-f65e67fe8a16\",\"formautofill@mozilla.org\":\"f0faeaf7-96ef-4dc6-b0b9-fad07d9718c4\",\"ipp-activator@mozilla.com\":\"32ed5529-671f-4fda-926e-d7b246c10ebf\",\"pictureinpicture@mozilla.org\":\"f73d1f18-2b0a-4396-8a29-a120517cdb5f\",\"addons-search-detection@mozilla.com\":\"b6e7ef51-bf8d-4164-82cf-d94788652350\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"88796299-f431-4233-be3e-9cb5d99ed0d6\",\"default-theme@mozilla.org\":\"b1c47362-82d6-48c0-b5f1-265c1649a327\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("nimbus.profileId", "e52bb758-ecbd-4e0b-8cf7-9f72ee0585ea");
user_pref("pdfjs.enabledCache.state", true);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1781022915);
user_pref("toolkit.telemetry.cachedClientID", "f36ad915-cde5-402b-98e4-5dfc48169f41");
user_pref("toolkit.telemetry.cachedProfileGroupID", "b3342fc4-9809-44a9-96fa-fe096cd10661");
user_pref("toolkit.telemetry.previousBuildID", "20260404010525");
